Repository C-Accel-CRIPT/Python-SDK, pull requests merged in 2023-08, with the labels that each got.

#243 refactor enum name from `ControlledVocabularyCategories` to `VocabCategories`
  docs/api/controlled_vocabulary_categories.md
  src/cript/__init__.py
  src/cript/api/__init__.py
  src/cript/api/api.py
  src/cript/api/vocabulary_categories.py
  src/cript/nodes/util/material_deserialization.py
  tests/api/test_api.py
Labels: refactor

#250 Handle empyt UUID correctly in JSON, by assigning new UUID
  src/cript/nodes/uuid_base.py
Labels: bug

#262 Std args json
  src/cript/nodes/core.py
  src/cript/nodes/primary_nodes/collection.py
  src/cript/nodes/primary_nodes/computation.py
  src/cript/nodes/primary_nodes/process.py
  src/cript/nodes/util/__init__.py
  tests/integration_test_helper.py
  tests/nodes/primary_nodes/test_collection.py
  tests/nodes/primary_nodes/test_computation.py
  tests/nodes/primary_nodes/test_experiment.py
  tests/nodes/primary_nodes/test_process.py
Labels: bug

#251 change the representation of UID
  src/cript/nodes/core.py
  src/cript/nodes/util/__init__.py
  src/cript/nodes/util/material_deserialization.py
  tests/conftest.py
  tests/integration_test_helper.py
  tests/nodes/primary_nodes/test_experiment.py
  tests/nodes/primary_nodes/test_project.py
  tests/test_node_util.py
Labels: bug

#292 upgraded requirements
  requirements.txt
  requirements_dev.txt
  requirements_docs.txt
Labels: dependencies

#306 updated file node doc with notes
  src/cript/nodes/supporting_nodes/file.py
Labels: documentation

#307 fixed `BIGSMILES` search test
  src/cript/api/api_config.py
  tests/api/test_api.py
Labels: bug
